name: deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
    - name: Setup Hugo
      run: |
        curl -L https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_linux-64bit.tar.gz | tar -xz
        sudo mv hugo /usr/local/bin/hugo
      env:
        HUGO_VERSION: 0.60.1
    - name: generate
      run: hugo
      env:
        HUGO_ENV: production
